# Generated by Django 5.0.3 on 2024-03-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_project_proj_total_shapes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_total_rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_total_shapes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_total_stitches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shape',
            name='total_rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shape',
            name='total_stitches',
            field=models.IntegerField(default=0),
        ),
    ]
